
version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quicksale
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  auth-service:
    build: ./auth-service
    depends_on: [mysql, kafka]
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=quicksale
      - KAFKA_BROKERS=kafka:9092

  inventory-service:
    build: ./inventory-service
    depends_on: [mysql, kafka]
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=quicksale
      - KAFKA_BROKERS=kafka:9092

  order-service:
    build: ./order-service
    depends_on: [mysql, kafka]
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=quicksale
      - KAFKA_BROKERS=kafka:9092

  notifier-service:
    build: ./notifier-service
    depends_on: [mysql, kafka]
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=quicksale
      - KAFKA_BROKERS=kafka:9092

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on: [auth-service, order-service, redis]
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9092

volumes:
  mysql-data:
